Repository windbase/windbase, pull requests merged in 2025-07, with the labels that each got.

#8 feat(toolbar): add functionality to preview HTML content in a new window
  apps/web/src/components/ui-navigation/toolbar.tsx
Labels: Review effort 2/5, Possible security concern

#9 Update README.md
  README.md
Labels: Review effort 1/5

#17 feat: add keyboard shortcuts for element deletion in ElementLayers co…
  apps/web/src/components/element-management/element-layers.tsx
Labels: Review effort 2/5

#19 Monaco Code Editor
  apps/web/package.json
  apps/web/src/components/core-builder/import-button.tsx
  apps/web/src/components/shared/code-editor.tsx
  pnpm-lock.yaml
Labels: Review effort 3/5

#32 Feat/blocks and templates
  apps/web/src/components/builder/block-picker.tsx
  apps/web/src/components/builder/live-preview/area.tsx
  apps/web/src/components/builder/sidebar-right.tsx
  apps/web/src/components/builder/template-picker.tsx
  apps/web/src/components/builder/toolbar/index.tsx
  apps/web/src/components/builder/visual-builder.tsx
  apps/web/src/components/shared/empty-elements.tsx
  packages/engine/src/template/index.ts
  packages/templates/README.md
  packages/templates/package.json
  packages/templates/src/categories/cta.ts
  packages/templates/src/categories/index.ts
  packages/templates/src/components/blocks/cta/cta-01.tsx
  packages/templates/src/components/blocks/cta/cta-02.tsx
  packages/templates/src/components/blocks/navbar/navbar-01.tsx
  packages/templates/src/components/templates/landing-page-01.tsx
  packages/templates/src/definitions/categories.ts
  packages/templates/src/definitions/define-template.ts
  packages/templates/src/definitions/types.ts
  packages/templates/src/index.ts
  packages/templates/src/register-blocks.ts
  packages/templates/src/register-templates.ts
  packages/templates/src/registry.ts
  packages/templates/tsconfig.json
  packages/templates/tsconfig.lib.json
  packages/templates/vite.config.ts
  pnpm-lock.yaml
Labels: Review effort 4/5

#36 fix: disable search textbox in layers panel to resolve issue #22
  apps/web/src/components/elements/layers.tsx
Labels: Review effort 1/5

#39 feat: setup vitest for store helpers [ci skip]
  .gitignore
  nx.json
  package.json
  packages/engine/src/store/__tests__/error-handling.test.ts
  packages/engine/src/store/__tests__/helpers.test.ts
  packages/engine/src/store/__tests__/integration.test.ts
  packages/engine/src/store/__tests__/persistence.test.ts
  packages/engine/src/store/__tests__/setup.ts
  packages/engine/src/store/__tests__/store-creation.test.ts
  packages/engine/src/store/__tests__/type-safety.test.ts
  packages/engine/tsconfig.json
  packages/engine/tsconfig.lib.json
  packages/engine/tsconfig.spec.json
  packages/utils/src/dom-element-to-builder-element.ts
  vitest.workspace.ts
Labels: Review effort 2/5

#52 fix: implement word-based undo functionality
  packages/engine/src/history/index.ts
  packages/engine/src/manipulation/index.ts
  packages/engine/src/store/__tests__/setup.ts
  packages/engine/src/store/__tests__/store-creation.test.ts
  packages/engine/src/store/__tests__/type-safety.test.ts
  packages/engine/src/store/types.ts
  packages/engine/src/template/index.ts
Labels: Review effort 3/5
